### PR TITLE
Implementing the Error trait on NFDError

### LINKED ISSUE #7: Implement std::error::Error for NFDError
`NFDError` is missing `Error` implementation. It should be easy to either write it manually or use e.g. `thiserror` to derive it.

### PR DESCRIPTION
**Pull request by sunjay**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

Added an implementation of `std::error::Error` for `NFDError`. Used `error::Error` instead of just importing `Error` because I noticed that the rest of the file used a similar convention. 

Thanks for maintaining this crate! Please release a new version once this is merged. :)

### Related Issues

Fixes #7

### CODE REVIEW

**Review by Jake-Shadle — APPROVED** [review]
Thanks!

**Comment by sunjay** [comment]
@Jake-Shadle Could someone release a new version of `nfd2` with the latest changes?

**Comment by Jake-Shadle** [comment]
This was released in 0.2.1 just now. :slightly_smiling_face:

**Comment by sunjay** [comment]
Thank you!

**Pull request merged**
